openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API to manage tasks (CRUD)

servers:
  - url: http://localhost:5000/api

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: OK
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found
        '404':
          description: Not Found

    put:
      summary: Update a task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Updated

    delete:
      summary: Delete a task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted

components:
  schemas:
    Task:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
